
# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'

set-option -g prefix C-a
unbind-key C-b
bind-key C-a send-prefix

# Split horizontally with Ctrl-a -
bind-key - split-window -v

# Split vertically with Ctrl-a |
bind-key | split-window -h

set-option -g base-index 1
set-option -g pane-base-index 1

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
