# Prefix key
set-option -g prefix C-a
unbind-key C-b
bind-key C-a send-prefix
unbind Space

# Reload config
unbind r
bind r source-file -F '#{@tmux_config_dir}/tmux.conf'

# Window management
unbind c
bind c new-window -c "#{pane_current_path}"

# Pane splitting
unbind %
bind | split-window -h -c "#{pane_current_path}"
unbind '"'
bind - split-window -v -c "#{pane_current_path}"

# Pane resizing
bind -r j resize-pane -D 5
bind -r k resize-pane -U 5
bind -r l resize-pane -R 5
bind -r h resize-pane -L 5
bind -r m resize-pane -Z

# Copy mode
unbind v
bind v copy-mode
bind-key -T copy-mode-vi 'v' send -X begin-selection
bind-key -T copy-mode-vi 'y' send -X copy-selection
bind-key -T copy-mode-vi v send-keys -X begin-selection

# Window mode switching (live, no reload needed)
# M- = Alt key. See windows_indexed.conf and windows_labeled.conf for what each mode does
bind-key M-i source-file -F '#{@tmux_config_dir}/conf/windows_indexed.conf'
bind-key M-l source-file -F '#{@tmux_config_dir}/conf/windows_labeled.conf'

# Session management
bind-key -r F run-shell "tmux neww ~/.local/bin/tmux_sessionizer.sh"
bind-key -r f run-shell "~/.local/bin/tmux_setup.sh"

bind-key + command-prompt "new-session -s '%%'"
