# =============================================================================
# Custom modules (must be sourced after catppuccin.tmux runs)
# =============================================================================

source-file -F '#{d:current_file}/custom_modules/session.conf'
source-file -F '#{d:current_file}/custom_modules/application.conf'
source-file -F '#{d:current_file}/custom_modules/directory.conf'
source-file -F '#{d:current_file}/custom_modules/gitmux.conf'
source-file -F '#{d:current_file}/custom_modules/weather.conf'
source-file -F '#{d:current_file}/custom_modules/battery.conf'
source-file -F '#{d:current_file}/custom_modules/zoom.conf'
source-file -F '#{d:current_file}/custom_modules/ctp_cpu.conf'
source-file -F '#{d:current_file}/custom_modules/ctp_memory.conf'
source-file -F '#{d:current_file}/custom_modules/online_status.conf'
source-file -F '#{d:current_file}/custom_modules/date_time.conf'

# =============================================================================
# Overall settings
# =============================================================================

# Status bar
set -g status-position top
set -g status-justify "absolute-centre"

# Pane border
setw -g pane-border-status top
setw -g pane-border-format ""

# =============================================================================
# Left
# =============================================================================

set -g status-left-length 200
set -g status-left ""
set -ag status-left '#{E:@catppuccin_status_session}'
set -ag status-left '#{E:@catppuccin_status_application}'
set -ag status-left '#{E:@catppuccin_status_directory}'
set -ag status-left '#{E:@catppuccin_status_gitmux}'
set -ag status-left '#{?window_zoomed_flag,#{E:@catppuccin_status_zoom},}'

# =============================================================================
# Right
# =============================================================================

set -g status-right-length 100
set -g status-right ""

if 'test -r /sys/class/power_supply/BAT*' {
  set -agF status-right '#{E:@catppuccin_status_battery}'
}
set -ag status-right '#{E:@catppuccin_status_weather}'
set -agF status-right '#{E:@catppuccin_status_online_status}'
set -agF status-right '#{E:@catppuccin_status_ctp_cpu}'
set -agF status-right '#{E:@catppuccin_status_ctp_memory}'
set -ag status-right '#{E:@catppuccin_status_date_time}'
