# Window mode: labeled
# When pane runs zsh: show basename of current path. Otherwise: show process name.
# Switch to indexed mode: prefix + M-i

run 'echo labeled > ~/.config/tmux/window_mode'
set -g allow-rename off
set -g automatic-rename-format "#{?#{==:#{pane_current_command},zsh},#{b:pane_current_path},#{pane_current_command}}"
set -g window-status-format " #I: #W "
set -g window-status-current-format " #I: #W "