tmux:
  symbols:
    branch: " "
    hashprefix: ":"
    ahead: "↑·"
    behind: "↓·"
    staged: "● "
    conflict: "✖ "
    modified: "✚ "
    untracked: "… "
    stashed: "⚑ "
    clean: ""
  styles:
    clear: "#[none]"
    state: "#[fg=colour1,bold]"
    branch: "#[fg=colour4]"
    remote: "#[fg=colour6]"
    divergence: "#[fg=colour3]"
    staged: "#[fg=colour2]"
    conflict: "#[fg=colour1]"
    modified: "#[fg=colour3]"
    untracked: "#[fg=colour4]"
    stashed: "#[fg=colour5]"
    clean: "#[fg=colour2]"
  layout: [branch, divergence, " ", flags]
  options:
    branch_max_len: 24
    branch_trim: right
    ellipsis: "…"
    hide_clean: false