%hidden MODULE_NAME="battery"

set -gq "@catppuccin_${MODULE_NAME}_icon" ' #{l:#{battery_icon_status}} '
set -gq "@catppuccin_${MODULE_NAME}_color" '#{l:#(#{@tmux_config_dir}/scripts/battery_color.sh)}'
set -gq "@catppuccin_${MODULE_NAME}_text" ' #{l:#{battery_percentage}}% '

set -gq "@catppuccin_status_${MODULE_NAME}_icon_bg" '#{l:#(#{@tmux_config_dir}/scripts/battery_color.sh)}'
set -gu "@catppuccin_status_${MODULE_NAME}_text_bg"
set -gq "@catppuccin_status_${MODULE_NAME}_text_fg" '#{l:#(#{@tmux_config_dir}/scripts/battery_color.sh)}'
source -F '#{d:current_file}/../../plugins/tmux/utils/status_module.conf'
