%hidden MODULE_NAME="date_time"

set -gq "@catppuccin_${MODULE_NAME}_icon" ' 󰃰 '
set -gqF "@catppuccin_${MODULE_NAME}_color" '#{E:@thm_sapphire}'
set -gq "@catppuccin_${MODULE_NAME}_text" ' %Y-%m-%d %H:%M '

# Force icon_bg to recalculate on reload (status_module.conf skips it if already set)
set -gu "@catppuccin_status_${MODULE_NAME}_icon_bg"
set -gu "@catppuccin_status_${MODULE_NAME}_text_bg"
set -gu "@catppuccin_status_${MODULE_NAME}_text_fg"
set -gq "@catppuccin_status_${MODULE_NAME}_text_fg" "#{@catppuccin_${MODULE_NAME}_color}"
source -F '#{d:current_file}/../../plugins/tmux/utils/status_module.conf'
