%hidden MODULE_NAME="online_status"

set -gq "@catppuccin_${MODULE_NAME}_icon" '#{?#{==:#{online_status},ok}, 󰖩 , 󰖪 }'
set -gq "@catppuccin_${MODULE_NAME}_color" '#{?#{==:#{online_status},ok},#{@thm_mauve},#{@thm_red}}'
set -gq "@catppuccin_${MODULE_NAME}_text" ' #{?#{==:#{online_status},ok},on,off} '

# Force icon_bg to recalculate on reload (status_module.conf skips it if already set)
set -gu "@catppuccin_status_${MODULE_NAME}_icon_bg"
set -gu "@catppuccin_status_${MODULE_NAME}_text_bg"
set -gu "@catppuccin_status_${MODULE_NAME}_text_fg"
set -gq "@catppuccin_status_${MODULE_NAME}_text_fg" "#{@catppuccin_${MODULE_NAME}_color}"
source -F '#{d:current_file}/../../plugins/tmux/utils/status_module.conf'
