# Catppuccin theme customization
set -g @catppuccin_flavor "mocha"                      # Use the mocha variant
set -g @catppuccin_status_background "none"            # Transparent background for status bar
set -g @catppuccin_window_status_style "none"          # Minimal styling for window status
set -g @catppuccin_pane_status_enabled "off"           # Disable additional pane indicators
set -g @catppuccin_pane_border_status "off"            # Disable pane border styling

#### Status bar customization ####
set -g status-position bottom
set -g status-style "bg=#{@thm_bg}"
set -g status-justify "absolute-centre"

#### Status bar - Left section ####

# Set the maximum length of the left status bar to 100 characters
set -g status-left-length 100
# Clear any existing content in the left status bar
set -g status-left ""
# If prefix key is pressed the session name is highlighted
set -ga status-left "#{?client_prefix,#{#[bg=#{@thm_red},fg=#{@thm_bg},bold]  #S },#{#[bg=#{@thm_bg},fg=#{@thm_green}]  #S }}"
# Append a separator |  
set -ga status-left "#[bg=#{@thm_bg},fg=#{@thm_overlay_0},none]│"
# Append current directory path, replace home directory with ~
set -ga status-left "#[bg=#{@thm_bg},fg=#{@thm_blue}]  #{=/-32/...:#{s|$USER|~|:#{b:pane_current_path}}} "

# If zoomed, append a separator |
set -ga status-left "#[bg=#{@thm_bg},fg=#{@thm_overlay_0},none]#{?window_zoomed_flag,│,}"
# If zoomed, append label "zoom"
set -ga status-left "#[bg=#{@thm_bg},fg=#{@thm_yellow}]#{?window_zoomed_flag,  zoom ,}"

#### Status bar - Right section ####

# Set the maximum length of the right status bar to 100 characters
set -g status-right-length 100
# Clear any existing content in the right status bar
set -g status-right ""
# Append battery status with conditional styling, different color depending on the battery_percentage 
set -ga status-right "#{?#{e|>=:10,#{battery_percentage}},#{#[bg=#{@thm_red},fg=#{@thm_bg}]},#{#[bg=#{@thm_bg},fg=#{@thm_pink}]}} #{battery_icon} #{battery_percentage} "
# Append a separator |  
set -ga status-right "#[bg=#{@thm_bg},fg=#{@thm_overlay_0}, none]│"
# Append online status with conditional styling, depending on network status
set -ga status-right "#[bg=#{@thm_bg}]#{?#{==:#{online_status},ok},#[fg=#{@thm_mauve}] 󰖩 on ,#[fg=#{@thm_red},bold]#[reverse] 󰖪 off }"

# Window and pane behavior
set -wg automatic-rename on                                                       # Automatically rename windows
set -g automatic-rename-format "#{pane_current_command}"                          # Use active command for renaming
set -g window-status-format " #I#{?#{!=:#{window_name},Window},: #W,} "           # If the window name is "Window" don't print the window name
set -g window-status-style "bg=#{@thm_bg},fg=#{@thm_rosewater}"
set -g window-status-current-format " #I#{?#{!=:#{window_name},Window},: #W,} "
set -g window-status-current-style "bg=#{@thm_peach},fg=#{@thm_bg},bold"
